/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import AirdropContractAbi from "../../hardhat/constants/abis/AirdropContract.json";
import BondingCurveAbi from "../../hardhat/constants/abis/BondingCurve.json";
import HypeFiAbi from "../../hardhat/constants/abis/Cult.json";
import HypeFiFactoryAbi from "../../hardhat/constants/abis/CultFactory.json";
import HypeFiRewardsAbi from "../../hardhat/constants/abis/CultRewards.json";
import { Abi } from "viem";
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  1114: {
    HypeFiRewards: {
      address: "0xb6Fc949059b4636E34bD28B1245832270Fe5d17a",
      abi: HypeFiRewardsAbi as Abi,
      inheritedFunctions: {},
      deploymentFile: "",
      deploymentScript: "deploy.js",
      constructorArgs: [],
      verified: false,
    },
    BondingCurve: {
      address: "0xe4D80ED5C8344A129535895255814e57f131c4CD",
      abi: BondingCurveAbi as Abi,
      inheritedFunctions: {},
      deploymentFile: "",
      deploymentScript: "deploy.js",
      constructorArgs: [],
      verified: false,
    },
    AirdropContract: {
      address: "0xac9A9B500a313f4c1B980b4492d3F436376F9776",
      abi: AirdropContractAbi as Abi,
      inheritedFunctions: {},
      deploymentFile: "",
      deploymentScript: "deploy.js",
      constructorArgs: [],
      verified: false,
    },
    HypeFi: {
      address: "0x2589D7228869e62a2a805daa8CF46B325380Cd07",
      abi: HypeFiAbi as Abi,
      inheritedFunctions: {},
      deploymentFile: "",
      deploymentScript: "deploy.js",
      constructorArgs: [
        "0x60187Bc4949eE2F01b507a9F77ad615093f44260",
        "0xb6Fc949059b4636E34bD28B1245832270Fe5d17a",
        "0x261D8c5e9742e6f7f1076Fa1F560894524e19cad",
        "0x50ff23E9A8D5DAc05744C367c9DDd588D027982B",
        "0x201B36B26b816D061fC552B679f8279Db0Fbbc6A",
      ],
      verified: false,
    },
    HypeFiFactory: {
      address: "0x4595c0Fa428e4BE211566237041D1e4FEac7fda4",
      abi: HypeFiFactoryAbi as Abi,
      inheritedFunctions: {},
      deploymentFile: "",
      deploymentScript: "deploy.js",
      constructorArgs: [],
      verified: false,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
